stages:          # List of stages for jobs, and their order of execution
  - test
  
run-e2e-tests:   # This job also runs in the test stage
  image: cypress/browsers:node14.19.0-chrome100-ff99-edge
  stage: test    # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "$CI_JOB_ID"
    - npm ci
    - npm run run:all
    - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/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 npx cypress-slack-reporter --ci-provider custom --custom-url=https://aldronnikov-projects.gitlab.io/-/cv-vue/-/jobs/$CI_JOB_ID/artifacts
  artifacts:
    name: "$CI_JOB_NAME-$CI_JOB_ID"
    when: always
    paths:
      - "**/mochareports/"
    expire_in: 30 days
