stages:          # List of stages for jobs, and their order of execution
  - test
  - upload


generate-report:
  stage: upload
  script:
    - echo "Hello world"
  artifacts:
    when: always
    paths:
      - "mochareports/assets"
    reports:
      junit: cypress/results_junit/combined-report.xml
    expire_in: 30 days
