stages:          # List of stages for jobs, and their order of execution
  - test
  
run-e2e-tests:   # This job also runs in the test stage
  image: cypress/browsers:node14.19.0-chrome100-ff99-edge
  stage: test    # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo $CI_JOB_ID
    - npm ci
    - npm run run:e2e
  artifacts:
    name: "$CI_JOB_NAME"
    when: always
    paths:
      - "cypress/reports/html"
    expire_in: 30 days
