import './components/ui/AppAbout.cy'
import './components/ui/AppButton.cy'
import './components/ui/AppHeading.cy'
import './components/ui/AppIcon.cy'
import './components/ui/AppInput.cy'
import './components/ui/AppListTitle.cy'
import './components/ui/AppLoader.cy'
import './components/ui/AppModal.cy'
import './components/ui/AppToast.cy'
import './components/ui/AppAbout.cy'

import './components/links/LinksList.cy'
import './components/links/LinksListItem.cy'

import './components/contacts/ContactsListItem.cy'
import './components/contacts/ContactsList.cy'